# Sleep a los 3 minutos
CONFIG_ZMK_IDLE_TIMEOUT=180000

# RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y

# RGB Backlight
CONFIG_ZMK_RGB_BACKLIGHT=n

# Sensores
CONFIG_ZMK_SENSOR=n

# Deep Sleep
CONFIG_ZMK_DEEP_SLEEP=y

# Bluetooth
CONFIG_ZMK_BLE=y
