# =========================
# SLEEP / AHORRO DE ENERGÍA
# =========================

# Habilita el modo de suspensión profunda (Deep Sleep)
CONFIG_ZMK_SLEEP=y

# Tiempo para entrar en Deep Sleep tras inactividad (en milisegundos)
# 180000 ms = 3 minutos
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=180000


# =========================
# RGB UNDERGLOW
# =========================

# Habilita el soporte para RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y

# Apaga el RGB automáticamente al estar en reposo/suspensión
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y

# RGB encendido al arrancar
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

# Apaga los LEDs cuando entra en inactividad
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# Efecto inicial
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1

# Velocidad inicial
CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=3

# Brillo inicial
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50


# =========================
# OTROS
# =========================

# Desactiva el Backlight por tecla
CONFIG_ZMK_BACKLIGHT=n

# Sensores / Encoders
CONFIG_ZMK_SENSOR=n

# Bluetooth
CONFIG_ZMK_BLE=y
